name: build

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
          npm ci
          npm run test:ci
          npm run codecov
